### ISSUE TITLE
When I import this by nuget-for-unity, got error

### ISSUE THREAD

**Issue by monkeyfuckeddog** [Abc-Arbitrage/Zebus#107]
Unloading broken assembly Assets/Packages/protobuf-net.Core.3.0.73/lib/netstandard2.0/protobuf-net.Core.dll, this assembly can cause crashes in the runtime

**Comment by MendelMonteiro** [comment]
Zebus relies heavily on `protobuf-net` for serialisation.  If the `protobuf-net.Core.3.0.73` assembly does not work in Unity then that would prevent Zebus from working as well.
Is there any further information you could provide?

**Comment by monkeyfuckeddog** [comment]
I fixed this.
It's because the dependency of System.Collections.Immutable.After I copy this dll file to unity, the error log disappear.

**Comment by monkeyfuckeddog** [comment]
Got it！

**Comment by monkeyfuckeddog** [comment]
Got it！
