### ISSUE TITLE
Use a buffer pool for message serialization

### ISSUE THREAD

**Issue by ocoanet** [Abc-Arbitrage/Zebus#42]
The message serialization process consists of 2 steps:
1. The IMessage serialization, which is performed on the thread that sends the message.
2. The TransportMessage serialization, which is performed on the OutboundProc of the ZmqTransport.

Because the step (2) is always performed in the same thread, it always reuses the same buffer.
However the step (1) creates new buffers in a very naive way:

``` cs
public byte[] Serialize(IMessage message)
{
    var stream = new MemoryStream();
    _serializer.Serialize(stream, message);

    return stream.ToArray();
}
```

These buffer allocations are quite problematic, especially for services that regularly send large messages, because they can generate LOH fragmentation.

We should use a buffer pool to avoid excessive buffer allocation and LOH fragmentation. We could use a general purpose pool (https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream) or use a custom pool.

**Comment by ablanchet** [comment]
Fixed in Zebus 2
