### ISSUE TITLE
Will this work on .netcore?

### ISSUE THREAD

**Issue by BenDerPan** [Abc-Arbitrage/Zebus#67]
Will this work on .netcore?

**Comment by ltrzesniewski** [comment]
No, as there's no netstandard or netcore build... at least yet.

We'd most probably have to either get rid of the clrzmq dependency by substituting it with something else, or port it to netstandard. We *may* do this at some point in the future, but we currently have no plans for this.

**Comment by BenDerPan** [comment]
thanks for your fast reply :)
