### ISSUE TITLE
Timeouts from the storage should be handled by the InMemoryMessageMatcher

### ISSUE THREAD

**Issue by ltrzesniewski** [Abc-Arbitrage/Zebus#73]
_From @alprema on March 15, 2016 10:20_

Since the `IStorage.Write()` method returns a Task, it should be waited by [InMemoryMessageMatcher](https://github.com/Abc-Arbitrage/Zebus.Persistence/blob/master/src/Abc.Zebus.Persistence/Matching/InMemoryMessageMatcher.cs#L164) in order to catch exceptions.

_Copied from original issue: Abc-Arbitrage/Zebus.Persistence#3_

**Comment by MendelMonteiro** [comment]
Was fixed by https://github.com/Abc-Arbitrage/Zebus/commit/38bd7c5da27bcd83c4870477858c8f0b6dcef7da
