### ISSUE TITLE
Can't install Abc.Zebus.Contracts

### ISSUE THREAD

**Issue by TipsyFingers** [Abc-Arbitrage/Zebus#76]
Hello everyone,

I am trying to use this library but I am not able to install needed NuGet.
I can install Zebus NuGetPackage version 3.1.0 but when I try to install Zebus.Contracts version 3.0.0 (latest version today) i get following error message:

> Could not install package 'Zebus.Contracts 3.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Is there any way to use this library with v4.0 framework?

**Comment by ltrzesniewski** [comment]
Hello,

Sorry but even if you could install Zebus.Contracts, the main Zebus package wouldn't work either, as we don't support .NET 4.0. I'm not even sure if we ever did.

The packages are currently targeting netstandard2.0, which means you need at least .NET 4.6.1.

Please note that Microsoft ended support of .NET 4.0 in january 2016. You should consider an upgrade.

**Comment by ablanchet** [comment]
Actually referencing netstandard20 assembly from .NET 4.6.1 seems to cause binding issues with certain assemblies. For example I had an issue with System.Net.Http, and Marc Gravell (@marcgravell) had recently a similar issue with System.Numerics.Vector. 

Long story short, [in this thread](https://twitter.com/terrajobst/status/1031999730320986112) Immo Landwerth (@terrajobst) -the guy taking care of .NET Standard at MS- explained that they had issues with .NET 4.6.1, and it's now recommended to be in .NET 4.7.2 to reference netstandard20 assemblies. 
The official communication about that is expected next week.
