### ISSUE TITLE
OldestNonAckedMessageTimestampInTicks might advance too aggressively

### ISSUE THREAD

**Issue by ocoanet** [Abc-Arbitrage/Zebus#77]
It is one of those days when you look at old code and ask yourself, “What the heck was I thinking?”.

I said "I" although I am not the author of the code because I have looked at this method many times in the past few years without noticing anything.

Of course, I may be utterly wrong so feedback from the masterminds behind Zebus persistence would be much appreciated (@ablanchet @alprema).

Here is the method:
https://github.com/Abc-Arbitrage/Zebus/blob/860f2b00462175d8dde32d46b08d9f2dd91d0d53/src/Abc.Zebus.Persistence.CQL/PeriodicAction/OldestNonAckedMessageUpdaterPeriodicAction.cs#L48-L76

I see mainly two issues here:

1. Sending peers generate the message IDs, which include the message timestamps because they are type 1 UUIDs. Messages can obviously be received out of order, because of network delays or clock drifts. So, if a message with a higher timestamp gets acked before a message with a lower timestamp is persisted, the `OldestNonAckedMessageTimestampInTicks` with be increased and the message with the lower timestamp might not be replayed.

2. When no message is found, `OldestNonAckedMessageTimestampInTicks` is moved to `DateTime.UtcNow.Ticks`, that is, the persistence server DateTime. Again, because of clock drifts, the server DateTime could be ahead of the sending peer DateTime. Worst, most messages received by the persistence server are mostly “from the past” due to network delay, so moving `OldestNonAckedMessageTimestampInTicks` to the current DateTime seems quite dangerous.

Because `OldestNonAckedMessageTimestampInTicks` is just an optimization to make replay faster, there is absolutely no risk to have its value set in the past. However, settings its value slightly in the future is quite dangerous because it can generate lost messages.

I see a simple fix for both issues: Add a safety period when increasing `OldestNonAckedMessageTimestampInTicks`. This period would typically be around 10-15 minutes. It could be regarded as the maximum estimated network delay or clock drift of the system.

**Comment by alprema** [comment]
Regarding your issues:
1. I agree, a safety margin would make sense (and the "+ 1" ticks on line 75  might be a bit too optimistic ;) )
2. Same here, the safety margin does the trick
3. Actually if I am not mistaken, it seems that when all messages are acked, `lastMessageTimestamp` is set to the last acked message's timestamp, which in case of a not too active service can be far in the past, which defeats the purpose of the cleanup (but I agree it's a minor issue in case of a low volume service).

**Comment by ocoanet** [comment]
`lastMessageTimestamp + 1` seems clearly broken too. Even in a world with perfectly synchronized clock, two messages generated by two peers could have the exact same timestamp part, so the `+ 1` could skip an unacked message. It looks like our younger selves were quite naive!
