### ISSUE TITLE
real p2p application

### ISSUE THREAD

**Issue by furesoft** [Abc-Arbitrage/Zebus#94]
is it possible to write a real p2p application with automated peer discovery with your library?

**Comment by MendelMonteiro** [comment]
Could you provide more detail as to what your p2p application would be?

Current usages of Zebus are as a p2p message bus. The Directory is used for peer discovery and is fault tolerant but all peers must know of a Directory to connect to the bus.

**Comment by ocoanet** [comment]
In Zebus, every peer has the entire Directory state in memory. So it should not be too hard to make every peer behave like a Directory (i.e., respond to registration commands and publish peer events). The peers would save the peer list so it could be used as the list of potential contact point on restart. Yet, the peers would need an initial contact point for the first startup. So you would need a list of permanent peers that would act as default contact point and that would not be very different from the actual design. Also, you still would have to solve the dead peer detection issue.

In my view, if you do not like the idea of the Zebus Directory, it would be best to replace it with an external component, for example Zookeeper. You can implement IPeerDirectoryClient using an external configuration/storage component as long as the component supports change notifications.

**Comment by MendelMonteiro** [comment]
@furesoft Did our replies answer your question?  I will close this issue soon if we don't hear back from you.
